### PR TITLE
Add IP8M-2496 to support matrix

### PR DESCRIPTION
**Pull request by dshokouhi**
Tested out my new camera and its working well with HA integration that utilizes this package

### CODE REVIEW

**Comment by thefinalwolf** [comment]
@tchellomello I also have the same camera, but receive 404 errors, I’ve been in talks with one of the devs. 
Did you have to do anything special to get this working? I keep getting 404 errors even when hand jamming commands from the official HTTP API documentation.

**Comment by dshokouhi** [comment]
@thefinalwolf when I tested the camera I made sure to update to the latest firmware.  I don't get any 404's and the camera functions as expected with the Home Assistant integration that uses this library.

**Comment by thefinalwolf** [comment]
@dshokouhi Thanks for the info. My unit may be defective since it’s on the latest firmware and still has problems.
It’s as though the cgi-bin folder is missing.

**Comment by dshokouhi** [comment]
@thefinalwolf I just tested it again and its working fine with `cgi-bin/snapshot.cgi` and also the motion detector is working.  I did notice that when I kept the snapshot setting to `6` the call would timeout and/or give me a 500 error.  Lowering it to `5` fixed this so that might be firmware related.

**Comment by thefinalwolf** [comment]
@dshokouhi Got it working. I performed a config backup, factory reset, then config restore and now I’m able to use the API.

Not sure what happened there, but maybe it had acted up since the camera has never touched the internet; I had updated it right out of the box via a direct connection and a downloaded update file.

Still didn’t touch the internet with the reset, but it’s working nonetheless.

**Comment by thefinalwolf** [comment]
@dshokouhi One more thing, is this project able to support https? I searched around and it wasn’t clear based on the docs and open/closed issues. Sorry if this is covered somewhere; I didn’t see this when I searched around.

I ask because I was able to replicate the exact problem that had plagued me. When https is enabled on this Amcrest camera, the API commands stop working through http, even though you can still log into the camera via http (this threw me off earlier). It looks like the intended behavior for the camera.

**Comment by dshokouhi** [comment]
@thefinalwolf it looks like `http` is hardcoded actually https://github.com/tchellomello/python-amcrest/blob/master/src/amcrest/http.py#L76

**Pull request merged**
