### PR TITLE
Add audio/video enable properties

### PR DESCRIPTION
**Pull request by pnbruckner**
Add properties for determining if any audio/video streams are enabled, and corresponding setters to enable/disable audio/video. Bump version to 1.3.0.

### CODE REVIEW

**Comment by pnbruckner** [comment]
The reason I marked this WIP is I'd like for you to test this on whatever cameras you have. I know it works on my cameras (IP2M-841W/2.520.AC00.18.R/2017-06-29 & IP3M-943W/2.400.AC02.15.R/2017-07-31).

To  test:
```
from amcrest import AmcrestCamera
cam = AmcrestCamera(...).camera
cam.audio_enabled
cam.audio_enabled = False
cam.audio_enabled # should return False
cam.audio_enabled = True
cam.audio_enabled # should return True
```
Same for video, but `cam.video_enabled` instead.

Also, of course, let me know if I should change anything in the way I implemented it.

**Comment by pnbruckner** [comment]
@tchellomello @dougsland 

Hi guys. Have you had a chance to look this over? Thoughts?

The biggest question I have, besides whether or not, in general, this works on other camera models & firmware versions than I have, is if these lines are appropriate:

https://github.com/tchellomello/python-amcrest/blob/streaming-on-off/src/amcrest/video.py#L148-L155

They set the "SmartIR" mode so that the IR LEDs come on when necessary (when video is enabled), or are turned completely off (when the video stream is disabled.) Do all cameras support this feature? Should I make it a separate command that the HA component can use if/when necessary?

**Comment by pnbruckner** [comment]
@tchellomello @dougsland 

I'm assuming you guys are too busy to provide feedback, so I'll go ahead with this.

**Comment by tchellomello** [comment]
@pnbruckner It was a busy week!! It's an awesome addition :1st_place_medal:  

You rock!

**Pull request merged**
