### PR TITLE
http: make httpx follow redirects by default

### PR DESCRIPTION
**Pull request by rkben**
home-assistant/core/issues/65652

### CODE REVIEW

**Comment by flacjacket** [comment]
Nice! Thanks!

**Comment by flacjacket** [comment]
I just pushed a new release with this in it, are you planning to open the PR to bump the package version in Home Assistant?

**Comment by rkben** [comment]
I was not planning to, but I can if you like.

**Comment by flacjacket** [comment]
If you could, that would be a great help to close out the ticket you linked!

**Pull request merged**
