### PR TITLE
PTZ: PositionABS command added

### PR DESCRIPTION
**Pull request by mehdilauters**

### CODE REVIEW

**Comment by iwr-mmwave** [comment]
Is the PositionABS code still valid as a command? I have purchased two cameras IP2M-841B and IP4M-1051B that both have firmware version from 2019 on the camera. The other commands such as Position, Right, or Up work correctly but the PositionABS command returns "Error Bad Request!"

Does anyone have PositionABS working correctly on devices with newer firmware?

**Comment by NickWaterton** [comment]
I also have an IP2M-841B with firmware version from 2019 on the camera, and get the same problem PositionABS command returns "Error Bad Request!".

So i think this command is no longer valid on the latest firmware.

**Comment by dougsland** [comment]
Hi @mehdilauters could you please fix the conflict for a fresh review?

**Comment by dougsland** [comment]
> I also have an IP2M-841B with firmware version from 2019 on the camera, and get the same problem PositionABS command returns "Error Bad Request!".
> 
> So i think this command is no longer valid on the latest firmware.

Thanks for the comment @NickWaterton

**Comment by mehdilauters** [comment]
Sorry for the question but... How do I add new commits to this PR instead of creating a new one?

**Comment by flacjacket** [comment]
@mehdilauters it looks like there are still merge conflicts with master, you'll need to rebase or merge the current master to be able to merge this PR.

**Review by flacjacket — APPROVED** [review]
Great, thanks for the updates!

**Pull request merged**
