### PR TITLE
Add functionality to use additional channels

### PR DESCRIPTION
**Pull request by flacjacket**
Add additional methods to be able to use specified channels, allowing
this to be used with NVRs.  Currently, the `@property`'s read from
channel 0, change these methods to call into the new functions for the
channel it used previously, so these should not change behavior.

Behavioral changes include:
- Event.event_channels_happened returns a list of channels where the
  event has occurred, rather than the request output.  This simplifies
  the `is_x_detected` methods.
- The `Event.is_x_detected` methods return a list of channels where the
  event occurred, rathen than a bool of if the event occurred or not.
- `Video.video_in_option` returns a list of all option configurations
  for all channels, rather than just returning the first option.  All of
  the properties (eg `video_enabled` and `day_night_color`) are
  unchanged, as they check channel 0.
- Some of the `System` properties (eg `serial_number`) are split with
  `pretty()` to give just the value rather than the full message
  payload.

### CODE REVIEW

**Comment by flacjacket** [comment]
Note, this builds off #173, the proposed change here can be seen in the latest commit.

**Comment by flacjacket** [comment]
Hey @tchellomello @dougsland @pnbruckner, any chance some of these changes can be reviewed? I've been using a custom home assistant integration to be able to use my NVR, and would love to be able to push those changes upstream, but it requires the changes in the stack of PRs #173 #174 #175 #176, which replace the mega-PR #169. Apart from dropping Python 2 support (which is only done in the last PR), these should be a noop for current users. Let me know if there is any way to make those easier to review!

**Comment by akram** [comment]
thanks @flacjacket this is exactly what I wanted almost a year ago without having time to implement it !
and I am also using hassio integration, this is why I needed it !

**Comment by flacjacket** [comment]
@akram No problem! I'm planning to open some PRs against home assistant to be able to get this into the native integration this weekend, so hopefully that will be upstream soon.

**Comment by akram** [comment]
great news. That will be the perfect timing to do my yearly re-installation/upgrade of hassio.
Good to hear that!

**Pull request merged**
